//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeafFallEngine {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeafFallEngine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] en_us {
            get {
                object obj = ResourceManager.GetObject("en_us", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap icon_x32 {
            get {
                object obj = ResourceManager.GetObject("icon_x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap icon_x512 {
            get {
                object obj = ResourceManager.GetObject("icon_x512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 即将加载绝对路径的dll，请确保编译后执行！ 的本地化字符串。
        /// </summary>
        public static string Program_Main_ {
            get {
                return ResourceManager.GetString("Program_Main_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意: 调试模式当中! 的本地化字符串。
        /// </summary>
        public static string Program_Main_注意__调试模式当中_ {
            get {
                return ResourceManager.GetString("Program_Main_注意__调试模式当中_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ; 这里是程序主菜单
        ///@Menu name=&quot;MainWindowMenu&quot;
        ///    @Submenu &quot;操作&quot;
        ///        #MenuItem &quot;返回&quot;
        ///        #MenuItem type=&quot;separate&quot;
        ///        #MenuItem &quot;暂停&quot;
        ///        #MenuItem &quot;退出&quot;
        ///    @clr Submenu
        ///    ; 进度设置
        ///    @Submenu &quot;进度&quot;
        ///        #MenuItem &quot;上一选项&quot;
        ///        #MenuItem &quot;日志&quot;
        ///        #MenuItem type=&quot;separate&quot;
        ///        #MenuItem 自动播放 type=&quot;check&quot;
        ///        @Submenu &quot;自动播放速度&quot; type=&quot;choice&quot;
        ///            #MenuItem &quot;0.25x&quot;
        ///            #MenuItem &quot;0.5x&quot;
        ///            #MenuItem &quot;1.0x&quot;
        ///            #MenuItem &quot;1.25x&quot;
        ///            [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] zh_cn {
            get {
                object obj = ResourceManager.GetObject("zh_cn", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
